# Wave -2: Namespaces — must exist before anything else
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    argocd.argoproj.io/manifest-generate-paths: .
spec:
  project: default
  source:
    repoURL: https://github.com/2143-Labs/2143-59s
    targetRevision: refs/heads/master
    path: base
    directory:
      include: namespaces.yaml
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
