# Istio values — Hillsboro (US West)
---
meshConfig:
  accessLogFile: /dev/stdout
  defaultConfig:
    terminationDrainDuration: 45s

pilot:
  resources:
    requests:
      cpu: 100m
      memory: 512Mi

global:
  meshID: "mesh-hillsboro"
  network: "hillsboro-network"
  multiCluster:
    clusterName: "hillsboro"
