# Istio values — Ashburn (US East)
---
meshConfig:
  accessLogFile: /dev/stdout
  defaultConfig:
    terminationDrainDuration: 45s

pilot:
  resources:
    requests:
      cpu: 100m
      memory: 512Mi

global:
  meshID: "mesh-ashburn"
  network: "ashburn-network"
  multiCluster:
    clusterName: "ashburn"
