# cert-manager ClusterIssuer — Nuremberg (EU)
# DNS01 solver pointing at local PowerDNS.
# Ready for ApplicationSet migration.
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: john@9s.pics
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          rfc2136:
            nameserver: "k3s-nuremberg.9s.pics"
            tsigKeyName: "externaldns"
            tsigAlgorithm: "HMACSHA256"
            tsigSecretSecretRef:
              name: rfc2136-credentials
              key: rfc2136TsigSecret
