# k8gb values — Nuremberg (EU)
# Domain: 9s.pics
---
k8gb:
  clusterGeoTag: "eu-nuremberg"
  extGslbClustersGeoTags: "us-ashburn,us-hillsboro"
  reconcileRequeueSeconds: 10
  dnsZones:
    - parentZone: "9s.pics"
      loadBalancedZone: "lb.9s.pics"
  edgeDNSServers:
    - "1.1.1.1"
  splitBrainCheck: true
  splitBrainTXTTTL: 30

coredns:
  isClusterService: false
  serviceType: "LoadBalancer"

extdns:
  enabled: true
  interval: 20s
  domainFilters:
    - "9s.pics"
  txtPrefix: "k8gb-nur-"
  txtOwnerId: "k8gb-nur"
